# -*- coding: utf-8 -*-
"""Final Proj_Hsieh_Martin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NtOKqRr4NqXNxYffcp3fLDoTSIjmYeL1
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
import re
import time

file_id = '1sZ9SPJvOlGttYeVRt-ACWvyLM3SNexN-'
direct_link = f'https://docs.google.com/spreadsheets/d/{file_id}/export?format=xlsx'

full_df = pd.read_excel(direct_link)

ind_df = full_df[['Indicator', 'Is_Anagram', 'Is_Reversal', 'Is_Hidden', 'Is_Homophone', 'Is_Container',
    'Is_Positional', 'Is_Deletion', 'Is_Selection', 'Is_Other', 'Is_Synonym_or_Sub',
    'Is_AndLit', 'Is_Rebus']]

WIKI_API_URL = "https://cryptics.fandom.com/api.php"

INDICATOR_PAGES = {
    'anagram': ['List_of_anagram_indicators'],
    'reversal': ['List_of_reversal_indicators'],
    'homophone': ['List_of_homophone_indicators'],
    'container': ['List_of_container_and_contents_indicators'],
    'hidden_word': ['List_of_hidden_word_indicators'],
    'deletion': ['List_of_general_deletion_indicators', 'List_of_letter_deletion_indicators'],
    'selection': ['List_of_letter_selection_indicators'],
    'positional' : ['List_of_juxtaposition_indicators']
}

def fetch_fandom_api(page_slug):
    """Fetches indicator words from the Fandom Wiki using their MediaWiki API."""
    print(f"Fetching {page_slug} via API...")

    params = {
        'action': 'parse',
        'page': page_slug,
        'format': 'json',
        'prop': 'text'
    }

    headers = {
        'User-Agent': 'MinuteCrypticResearchBot/1.0 (Data Science Project) Python/Requests',
        'Accept': 'application/json'
    }

    indicators = []

    try:
        response = requests.get(WIKI_API_URL, params=params, headers=headers)
        response.raise_for_status()
        data = response.json()

        if 'parse' in data and 'text' in data['parse']:
            html_content = data['parse']['text']['*']
            soup = BeautifulSoup(html_content, 'html.parser')

            for li in soup.find_all('li'):
                text = li.get_text(strip=True)

                text = re.sub(r'\[\d+\]', '', text)
                text = text.replace('*', '').strip().lower()

                if 0 < len(text) < 35 and ':' not in text and 'list of' not in text and '^' not in text:
                    indicators.append(text)

        return list(set(indicators))

    except requests.exceptions.RequestException as e:
        print(f"Error fetching {page_slug}: {e}")
        return []


print("Building the Cryptic Lexicon...")
indicator_lexicon = {}

for category, slugs in INDICATOR_PAGES.items():
    combined_indicators = []

    for slug in slugs:
        combined_indicators.extend(fetch_fandom_api(slug))
        time.sleep(1.5)

    indicator_lexicon[category] = list(set(combined_indicators))

def get_lexicon():
    return indicator_lexicon

import re

def map_cryptic_indicators(row):
    raw_indicator_string = str(row['Indicator']).lower()

    type_columns = ['Is_Anagram', 'Is_Reversal', 'Is_Hidden', 'Is_Homophone', 'Is_Container',
                    'Is_Positional', 'Is_Deletion', 'Is_Selection']

    active_types = [col.replace('Is_', '').lower() for col in type_columns if row.get(col, 0) == 1]

    mapping = {}

    if len(active_types) == 1:
        isolated_indicators = [i.strip() for i in raw_indicator_string.split('|') if i.strip()]
        for ind in isolated_indicators:
            mapping[ind] = active_types[0]

        return mapping

    if len(active_types) > 1:
        raw_indicator_clean = raw_indicator_string.replace(',', ' ')

        for act_type in active_types:
            if act_type in indicator_lexicon:
                for known_word in indicator_lexicon[act_type]:
                    if re.search(r'\b' + re.escape(known_word) + r'\b', raw_indicator_clean):
                        mapping[known_word] = act_type

    return mapping

ind_df = ind_df.dropna(subset=['Indicator'])
ind_df = ind_df[~ind_df['Indicator'].astype(str).str.strip().str.upper().eq('NONE')]

ind_df['Mapped_Indicators'] = ind_df.apply(map_cryptic_indicators, axis=1)

cols_to_remove = ['Is_Other', 'Is_Rebus', 'Is_AndLit', 'Is_Synonym_or_Sub']

ind_df = ind_df[~(ind_df[cols_to_remove] == 1).any(axis=1)]

ind_df = ind_df.drop(columns=cols_to_remove, errors='ignore')

ambig_ind_df = ind_df[ind_df['Mapped_Indicators'] == {}]

pd.set_option('display.max_rows', None)
ambig_ind_df

ind_df.at[10, 'Mapped_Indicators'] = {'less' : 'deletion', 'boothed by' : 'container', 'uncouth' : 'anagram'}
ind_df.at[27, 'Mapped_Indicators'] = {'runners up' : 'selection', 'to Miss' : 'deletion'}
ind_df.at[46, 'Mapped_Indicators'] = {'busting' : 'anagram', 'duo to start' : 'selection'}
ind_df.at[59, 'Mapped_Indicators'] = {'prances' : 'anagram', 'adorning' : 'container', 'exterior of' : 'selection'}
ind_df.at[61, 'Mapped_Indicators'] = {'Leads from' : 'selection', 'interfere with' : 'container'}
ind_df.at[67, 'Mapped_Indicators'] = {'chewed' : 'anagram', 'leaves' : 'deletion', 'bark' : 'selection'}
ind_df.at[76, 'Mapped_Indicators'] = {'half' : 'selection', 'curiously' : 'selection'}
ind_df.at[96, 'Mapped_Indicators'] = {'swapped' : 'container', 'clothes with' : 'selection'}
ind_df.at[111, 'Mapped_Indicators'] = {'Swarming' : 'anagram', 'escape' : 'deletion'}
ind_df.at[133, 'Mapped_Indicators'] = {'first two' : 'selection', 'lost' : 'deletion'}
ind_df.at[156, 'Mapped_Indicators'] = {'thrown' : 'anagram', 'second on' : 'selection'}
ind_df.at[167, 'Mapped_Indicators'] = {'start, exiting' : 'deletion', 'roundabout' : 'deletion'}
ind_df.at[186, 'Mapped_Indicators'] = {'starts to' : 'selection', 'noisy' : 'anagram'}
ind_df.at[508, 'Mapped_Indicators'] = {'puzzle' : 'anagram', 'grips' : 'container', 'half of': 'selection'}
ind_df.at[395, 'Mapped_Indicators'] = {'circulating' : 'reversal', 'piece of' : 'hidden_word'}
ind_df.at[370, 'Mapped_Indicators'] = {'first' : 'selection', 'borderless' : 'deletion'}
ind_df.at[361, 'Mapped_Indicators'] = {'Foreign' : 'anagram', 'snubbed' : 'deletion', 'Chief of': 'selection'}
ind_df.at[332, 'Mapped_Indicators'] = {'chief' : 'selection', 'less' : 'deletion'}
ind_df.at[298, 'Mapped_Indicators'] = {'back' : 'reversal', 'packing' : 'hidden_word'}
ind_df.at[284, 'Mapped_Indicators'] = {'A selection of' : 'hidden_word', 'retro' : 'reversal'}
ind_df.at[260, 'Mapped_Indicators'] = {'Cancel' : 'deletion', 'even' : 'selection'}
ind_df.at[257, 'Mapped_Indicators'] = {'first' : 'selection', 'to do moonwalk' : 'reversal'}
ind_df.at[215, 'Mapped_Indicators'] = {'half' : 'selection', 'screwed' : 'reversal'}
ind_df.at[188, 'Mapped_Indicators'] = {'starting' : 'selection', 'to be captivated by' : 'container', 'looping': 'reversal'}
ind_df.at[187, 'Mapped_Indicators'] = {'starts' : 'selection', 'malfunctioning' : 'anagram'}
ind_df.at[314, 'Mapped_Indicators'] = {'revealing' : 'hidden_word'}

# convert DataFrame into sequences of words and their corresponding labels.
# tag the first word of an indicator as B-{type} (Beginning) and subsequent words as I-{type} (Inside)
# Everything else gets an O (Outside).

import pandas as pd
import re

ind_df['Clue'] = full_df['Clue']

def create_bio_tags(row):
    clue = str(row['Clue']).lower()
    words = re.findall(r"[\w']+|[.,!?;]", clue)

    tags = ['O'] * len(words)
    mapped_inds = row.get('Mapped_Indicators', {})

    if not isinstance(mapped_inds, dict) or len(mapped_inds) == 0:
        return {"words": words, "tags": tags}

    for ind_phrase, ind_type in mapped_inds.items():
        ind_words = re.findall(r"[\w']+|[.,!?;]", ind_phrase.lower())
        ind_len = len(ind_words)

        for i in range(len(words) - ind_len + 1):
            if words[i:i+ind_len] == ind_words:
                tags[i] = f"B-{ind_type}"
                for j in range(1, ind_len):
                    tags[i+j] = f"I-{ind_type}"

    return {"words": words, "tags": tags}

ind_df['NER_Data'] = ind_df.apply(create_bio_tags, axis=1)

# test print
print(ind_df['NER_Data'].iloc[0])

import pandas as pd
import random
import re

all_words = []
for clue in ind_df['Clue'].dropna():
    words = re.findall(r"[\w']+|[.,!?;]", str(clue).lower())
    all_words.extend(words)

all_indicator_words = set()
for d in ind_df['Mapped_Indicators']:
    if isinstance(d, dict):
        for phrase in d.keys():
            all_indicator_words.update(re.findall(r"[\w']+|[.,!?;]", phrase.lower()))

safe_vocab = list(set(all_words) - all_indicator_words)
safe_vocab = [w for w in safe_vocab if w.isalpha()]

def augment_clue(row, num_augments=5):
    clue = str(row['Clue']).lower()
    mapped_inds = row.get('Mapped_Indicators', {})

    if not isinstance(mapped_inds, dict) or len(mapped_inds) == 0:
        return [row.to_dict()]

    words = re.findall(r"[\w']+|[.,!?;]", clue)

    ind_indices = set()
    for ind_phrase in mapped_inds.keys():
        ind_words = re.findall(r"[\w']+|[.,!?;]", ind_phrase.lower())
        ind_len = len(ind_words)
        for i in range(len(words) - ind_len + 1):
            if words[i:i+ind_len] == ind_words:
                for j in range(ind_len):
                    ind_indices.add(i+j)

    augmented_rows = [row.to_dict()]

    for _ in range(num_augments):
        new_words = []
        for i, word in enumerate(words):
            if i in ind_indices or not word.isalpha():
                new_words.append(word)
            else:
                if random.random() < 0.50:
                    new_words.append(random.choice(safe_vocab))
                else:
                    new_words.append(word)

        new_clue = " ".join(new_words).replace(" ,", ",").replace(" .", ".").replace(" !", "!").replace(" ?", "?")

        new_row = row.to_dict()
        new_row['Clue'] = new_clue
        augmented_rows.append(new_row)

    return augmented_rows

print(f"Original dataset size: {len(ind_df)}")

aug_list = []
for _, row in ind_df.iterrows():
    aug_list.extend(augment_clue(row, num_augments=5))

ind_df = pd.DataFrame(aug_list)
print(f"Augmented dataset size: {len(ind_df)}")

# gather all the unique tags we just created, assign them an ID number
# load the data into a Hugging Face Dataset object to split into Train/Test/Validation sets

from datasets import Dataset, DatasetDict
import numpy as np

all_data = ind_df['NER_Data'].tolist()
words_list = [d['words'] for d in all_data]
tags_list = [d['tags'] for d in all_data]

unique_tags = set(tag for doc in tags_list for tag in doc)
label2id = {tag: id for id, tag in enumerate(sorted(unique_tags))}
id2label = {id: tag for tag, id in label2id.items()}

ner_tags_list = [[label2id[tag] for tag in doc] for doc in tags_list]

hf_dataset = Dataset.from_dict({
    "id": list(range(len(words_list))),
    "tokens": words_list,
    "ner_tags": ner_tags_list
})

train_test_split = hf_dataset.train_test_split(test_size=0.2, seed=42)
test_val_split = train_test_split['test'].train_test_split(test_size=0.5, seed=42)

final_dataset = DatasetDict({
    'train': train_test_split['train'],
    'validation': test_val_split['train'],
    'test': test_val_split['test']
})

print(f"Label Mapping: {label2id}")
print(final_dataset)

# Transformer models like DistilBERT use "subword tokenization" (e.g., splitting "busting" into "bust" and "##ing")
# When a word is split in half, we have to stretch our labels so the neural network knows both halves belong to the same indicator

from transformers import AutoTokenizer, DataCollatorForTokenClassification

model_checkpoint = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(examples["tokens"], truncation=True, is_split_into_words=True)

    labels = []
    for i, label in enumerate(examples["ner_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []
        for word_idx in word_ids:
            if word_idx is None:
                label_ids.append(-100)
            elif word_idx != previous_word_idx:
                label_ids.append(label[word_idx])
            else:
                current_label_id = label[word_idx]
                tag_str = id2label[current_label_id]

                if tag_str.startswith("B-"):
                    i_tag_str = "I-" + tag_str[2:]
                    label_ids.append(label2id[i_tag_str])
                else:
                    label_ids.append(current_label_id)

            previous_word_idx = word_idx
        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs

tokenized_datasets = final_dataset.map(tokenize_and_align_labels, batched=True)

data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

# use DistilBERT because it is fast, lightweight

from transformers import AutoModelForTokenClassification, TrainingArguments, Trainer

model = AutoModelForTokenClassification.from_pretrained(
    model_checkpoint,
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

training_args = TrainingArguments(
    output_dir="./minute_cryptic_model",
    eval_strategy="epoch",
    logging_strategy="epoch",
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    learning_rate=5e-5,
    lr_scheduler_type="cosine",
    warmup_ratio=0.1,
    num_train_epochs=6,
    weight_decay=0.01,
    fp16=False,
    dataloader_drop_last=True
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    processing_class=tokenizer,
    data_collator=data_collator,
)

print("Starting training...")
trainer.train()

trainer.save_model("minute-cryptic-indicator-ner")

import torch
from torch import nn
from transformers import Trainer, AutoModelForTokenClassification, TrainingArguments

model = AutoModelForTokenClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

training_args = TrainingArguments(
    output_dir="./minute_cryptic_model",
    eval_strategy="epoch",
    logging_strategy="epoch",
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    learning_rate=5e-5,
    lr_scheduler_type="cosine",
    warmup_ratio=0.1,
    num_train_epochs=6,
    weight_decay=0.01,
    fp16=False,
    dataloader_drop_last=True
)

class StableWeightedNERTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits
        weights = torch.ones(model.config.num_labels, device=model.device)
        o_tag_id = model.config.label2id['O']
        weights[o_tag_id] = 0.3

        loss_fct = nn.CrossEntropyLoss(weight=weights)

        active_loss = labels.view(-1) != -100
        active_logits = logits.view(-1, model.config.num_labels)[active_loss]
        active_labels = labels.view(-1)[active_loss]

        loss = loss_fct(active_logits, active_labels)

        return (loss, outputs) if return_outputs else loss

stable_trainer = StableWeightedNERTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    processing_class=tokenizer,
    data_collator=data_collator,
)

print("Starting stable weighted training...")
stable_trainer.train()

stable_trainer.save_model("minute-cryptic-indicator-ner-stable")

import numpy as np
import torch

all_tags = [tag for doc in tags_list for tag in doc]
total_tags = len(all_tags)
num_classes = len(unique_tags)

tag_counts = {}
for tag in all_tags:
    tag_counts[tag] = tag_counts.get(tag, 0) + 1

class_weights_dict = {}
for tag, count in tag_counts.items():
    weight = total_tags / (num_classes * count)
    class_weights_dict[tag] = weight

print("Calculated Class Weights:")
for tag, weight in sorted(class_weights_dict.items(), key=lambda item: item[1]):
    print(f"{tag}: {weight:.4f}")

weights_list = [0.0] * num_classes
for tag, id in label2id.items():
    weights_list[id] = class_weights_dict[tag]

pytorch_class_weights = torch.tensor(weights_list, dtype=torch.float32)

import torch
from torch import nn
from transformers import Trainer, AutoModelForTokenClassification

model = AutoModelForTokenClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

class WeightedNERTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        # Extract the labels and get the model's predictions
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        # Create weights for each class: default is 1.0
        num_labels = model.config.num_labels
        weights = pytorch_class_weights.to(model.device)

        # Apply the weighted loss function
        loss_fct = nn.CrossEntropyLoss(weight=weights)

        active_loss = labels.view(-1) != -100
        active_logits = logits.view(-1, num_labels)[active_loss]
        active_labels = labels.view(-1)[active_loss]

        loss = loss_fct(active_logits, active_labels)

        return (loss, outputs) if return_outputs else loss

training_args = TrainingArguments(
    output_dir="./minute_cryptic_model",
    eval_strategy="epoch",
    logging_strategy="epoch",
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    learning_rate=5e-5,
    lr_scheduler_type="cosine",
    warmup_ratio=0.1,
    num_train_epochs=6,
    weight_decay=0.01,
    fp16=False,
    dataloader_drop_last=True
)

weighted_trainer = WeightedNERTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    processing_class=tokenizer,
    data_collator=data_collator,
)

print("Starting weighted training...")
weighted_trainer.train()

weighted_trainer.save_model("minute-cryptic-indicator-ner-weighted")

import random

test_samples = final_dataset['test'].shuffle(seed=42).select(range(5))

def extract_full_indicators(text, threshold=0.50):
    raw_preds = ner_pipeline(text)

    extracted = {}
    for ent in raw_preds:
        if ent['score'] >= threshold and ent['entity_group'] != 'O':
            word = str(ent['word']).strip()
            extracted[word] = ent['entity_group']

    return extracted

def normalize_text(text):
    clean_text = str(text).lower().strip()
    clean_text = re.sub(r'\s*[-–—]\s*', '-', clean_text)
    clean_text = re.sub(r"\s*'\s*", "'", clean_text)
    return clean_text

human_labels = ind_df[['Clue', 'Mapped_Indicators']].copy()
human_labels = human_labels.rename(columns={'Mapped_Indicators': 'HUMAN_TRUTH'})
human_labels = human_labels.drop_duplicates(subset=['Clue'])

eval_df = full_df.merge(human_labels, on='Clue', how='inner')

eval_df = eval_df[eval_df['HUMAN_TRUTH'].notna() & (eval_df['HUMAN_TRUTH'].astype(str) != '{}')].copy()

def evaluate_at_threshold(test_df, threshold_value):
    total_actual = 0
    total_pred = 0
    exact_matches = 0

    for _, row in test_df.iterrows():
        raw_actual = row['HUMAN_TRUTH']
        raw_predicted = extract_full_indicators(row['Clue'], threshold=threshold_value)
        raw_predicted = raw_predicted if isinstance(raw_predicted, dict) else {}

        actual = {normalize_text(word): tag for word, tag in raw_actual.items()}
        predicted = {normalize_text(word): tag for word, tag in raw_predicted.items()}

        total_actual += len(actual)
        total_pred += len(predicted)

        for p_word, p_type in predicted.items():
            if p_word in actual and p_type == actual[p_word]:
                exact_matches += 1

    precision = (exact_matches / total_pred) * 100 if total_pred > 0 else 0
    recall = (exact_matches / total_actual) * 100 if total_actual > 0 else 0
    f1 = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

    return precision, recall, f1, total_pred

thresholds = [0.4, 0.5, 0.6, 0.65, 0.7, 0.75, 0.8, 0.9]

from transformers import pipeline

print("\n STABLE:")
ner_pipeline = pipeline(
    "ner",
    model="./minute-cryptic-indicator-ner-stable",
    tokenizer=tokenizer,
    aggregation_strategy="simple"
)
full_df['AI_Predicted_Indicators'] = full_df['Clue'].apply(extract_full_indicators)

results = []

print(f"{'Threshold':<10} | {'Precision':<10} | {'Recall':<10} | {'F1-Score':<10} | {'Guesses'}")
print("-" * 60)

for t in thresholds:
    p, r, f, g = evaluate_at_threshold(eval_df, t)
    results.append({"Threshold": t, "Precision": p, "Recall": r, "F1": f})
    print(f"{t:<10} | {p:0.1f}%     | {r:0.1f}%     | {f:0.1f}%     | {g}")

# ----------------------------------------------

print("\n BASE:")
ner_pipeline = pipeline(
    "ner",
    model="./minute-cryptic-indicator-ner",
    tokenizer=tokenizer,
    aggregation_strategy="simple"
)
full_df['AI_Predicted_Indicators'] = full_df['Clue'].apply(extract_full_indicators)

results = []

print(f"{'Threshold':<10} | {'Precision':<10} | {'Recall':<10} | {'F1-Score':<10} | {'Guesses'}")
print("-" * 60)

for t in thresholds:
    p, r, f, g = evaluate_at_threshold(eval_df, t)
    results.append({"Threshold": t, "Precision": p, "Recall": r, "F1": f})
    print(f"{t:<10} | {p:0.1f}%     | {r:0.1f}%     | {f:0.1f}%     | {g}")

# ---------------------------------------

print("\n WEIGHTED:")
ner_pipeline = pipeline(
    "ner",
    model="./minute-cryptic-indicator-ner-weighted",
    tokenizer=tokenizer,
    aggregation_strategy="simple"
)
full_df['AI_Predicted_Indicators'] = full_df['Clue'].apply(extract_full_indicators)

results = []

print(f"{'Threshold':<10} | {'Precision':<10} | {'Recall':<10} | {'F1-Score':<10} | {'Guesses'}")
print("-" * 60)

for t in thresholds:
    p, r, f, g = evaluate_at_threshold(eval_df, t)
    results.append({"Threshold": t, "Precision": p, "Recall": r, "F1": f})
    print(f"{t:<10} | {p:0.1f}%     | {r:0.1f}%     | {f:0.1f}%     | {g}")

"""# Error Analysis"""

# stable -> highest precision/f1
ner_pipeline = pipeline(
    "ner",
    model="./minute-cryptic-indicator-ner-stable", # or BASE: ./minute-cryptic-indicator-ner
    tokenizer=tokenizer,
    aggregation_strategy="simple"
)

# threshold from table above
THRESHOLD = 0.5

false_negatives = []
false_positives = []
type_mismatches = []

for _, row in eval_df.iterrows():
    clue = str(row['Clue'])

    raw_human_truth = row['HUMAN_TRUTH'] if isinstance(row['HUMAN_TRUTH'], dict) else {}
    human_truth = {normalize_text(word): tag for word, tag in raw_human_truth.items()}

    # This now calls our hyper-clean pipeline wrapper!
    raw_preds = extract_full_indicators(clue, threshold=THRESHOLD)
    raw_preds = raw_preds if isinstance(raw_preds, dict) else {}

    ai_preds = {normalize_text(word): tag for word, tag in raw_preds.items()}

    for ai_word, ai_type in ai_preds.items():
        if ai_word not in human_truth:
            false_positives.append({"clue": clue, "word": ai_word, "ai_guessed": ai_type})
        elif human_truth[ai_word] != ai_type:
            type_mismatches.append({
                "clue": clue,
                "word": ai_word,
                "ai_guessed": ai_type,
                "human_truth": human_truth[ai_word]
            })

    for human_word, human_type in human_truth.items():
        if human_word not in ai_preds:
            false_negatives.append({"clue": clue, "word": human_word, "human_truth": human_type})

print("="*50)
print(f"ERROR REPORT (Threshold: {THRESHOLD})")
print("="*50)

print(f"\nFALSE NEGATIVES (AI Missed These - Total: {len(false_negatives)})")
print("-" * 50)
for error in false_negatives:
    print(f"Missed Word: '{error['word']}' (Type: {error['human_truth']})")
    print(f"Clue: {error['clue']}\n")

print(f"\nFALSE POSITIVES (AI Hallucinated These - Total: {len(false_positives)})")
print("-" * 50)
for error in false_positives:
    print(f"Hallucinated: '{error['word']}' (Guessed Type: {error['ai_guessed']})")
    print(f"Clue: {error['clue']}\n")

print(f"\nTYPE MISMATCHES (Wrong Category - Total: {len(type_mismatches)})")
print("-" * 50)
for error in type_mismatches:
    print(f"Word: '{error['word']}'")
    print(f"AI Guessed: {error['ai_guessed']} | Human Said: {error['human_truth']}")
    print(f"Clue: {error['clue']}\n")